# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cadfefd6b21ec627cab8949b9c417a63f501fd54d633cdc9ae8ff75f4c6e76bfe6cf7202b3e481892f5a0a71ed297a8b266e267031069b2fba4833c8cce0219

test:
  secret_key_base: a7d2d49b62cd0bb1815dcb68b630d3157fe2550594d5d410bb8a5beb0b0f9b4208f453bd5140231a6aca10f0a4b50c7d25d6f51298687e75d78c30b0367bf95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
